@startuml
:User: --> (001)
:User: --> (002)
:User: --> (003)

"[UC 011] PESQUISAR ESTABELECIMENTOS" as (001)
"[UC 012] VISUALIZAR ESTABELECIMENTOS NO MAPA" as (002)
"[UC 013] VISUALIZAR INFORMACOES SOBRE O ESTABELECIMENTO" as (003)


@enduml